<?php if ($this->getTotals()): ?>
    <dt class="complete">
        <?php echo $this->__('Your Order') ?> <span class="separator">|</span> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__("Edit Cart"); ?></a>
    </dt>
    <dd>
        <table id="cart-subtotal-table" class="data-table">
            <?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 5 : 3; ?>
            <?php echo $totals = $this->renderTotals(null, $_colspan); ?>
            <?php if(strpos($totals,"shipping")===false): ?>
                <tr id="cart-subtotal-table-shipping" class="cart-subtotal-table-row clearfix">
                    <th class="cart-subtotal-table-left"><?php echo $this->__("Shipping &amp; Handling:"); ?></th>
                    <td class="cart-subtotal-table-right" title="<?php echo $this->__("Your Order has qualified for Free Shipping!"); ?>"><?php echo $this->__("FREE"); ?></td>
                </tr>
            <?php endif; ?>
            <?php echo $this->renderTotals('footer', $_colspan); ?>
            <?php if ($this->needDisplayBaseGrandtotal()):?>
                <tr>
                    <td class="a-right" colspan="<?php echo $_colspan; ?>">
                        <small><?php echo $this->helper('sales')->__('Your credit card will be charged for') ?></small>
                    </td>
                    <td class="a-right">
                        <small><?php echo $this->displayBaseGrandtotal() ?></small>
                    </td>
                </tr>
            <?php endif?>
        </table>
    </dd>
<?php endif?>