<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection(); 
    $_helper = $this->helper('catalog/output');
	$imageWidth = Mage::getStoreConfig('quickview/frontend/listwidth');
	$imageHeight = Mage::getStoreConfig('quickview/frontend/listheight');	 
?>
<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<div class="category-products"> <?php echo $this->getToolbarHtml() ?>
  <?php // List mode ?>
  <?php if($this->getMode()!='grid'): ?>
  <?php $_iterator = 0; ?>
  <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
    <li class="fadeIn animated item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
      <?php // Product Image ?>
      <a id="<?php echo $_product->getId()?>" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img  src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageWidth,$imageHeight); ?>"></a>
      
 <?php if (Mage::getStoreConfig('quickview/settings/enabled')):?> 


 <span> <a class="quickview-button button fa-search-btn first-bg" href="javascript:void(0)" onclick="quickvieShow(this)"> <i class="icon-search"></i> </a></span>
 
 <?php endif ?>
      
      
      <div style="display: none;" class="quickview-loader" onclick="closePopup()" id="quickview-loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif')?>"></div>
      <div class="product-shop">
        <div class="no-fix">
          <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
          <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
          <?php if($_product->getRatingSummary()): ?>
          <div class="price-box"> <?php echo $this->getReviewsSummaryHtml($_product) ?></div>
          <?php endif; ?>
          <?php echo $this->getPriceHtml($_product, true) ?>
          <div class="desc std"> <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a></div>
        </div>
      </div>
      <div class="btn-set">
        <div class="actions">
          <?php if($_product->isSaleable()): ?>
          <a class="btn-circle first-bg-hover" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"> <i class="icon-shopping-cart"></i> </a>
          <?php else: ?>
          <?php endif; ?>
          <a class="btn-circle first-bg-hover" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"> <i class="icon-heart"></i></a>
          
        
           
             <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                              <a class="btn-circle first-bg-hover" href="<?php echo $_compareUrl ?>" > <i class="icon-exchange"></i></a>
                              
                              
                        <?php endif; ?>
           
           
            </div>
      </div>
    </li>
    <?php endforeach; ?>
  </ol>
  <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
  <?php else: ?>
  <?php // Grid Mode ?>
  <?php $_collectionSize = $_productCollection->count() ?>
  <?php $_columnCount = $this->getColumnCount(); ?>
  <?php $i=0; foreach ($_productCollection as $_product): ?>
  <?php if ($i++%$_columnCount==0): ?>
  <ul class="products-grid">
    <?php endif ?>
    <li class="fadeIn animated item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>"> 
    
    
  <?php 
															$hasSpecial = ($_product->getSpecialPrice())?true:false;
															$isNew = false;
															$newFrom = strtotime($_product->getNewsFromDate());
															$newTo = strtotime($_product->getNewsToDate());
															if (time()>$newFrom && time()<$newTo){
																$isNew = true;
															}
														?>
      <?php if ($hasSpecial):?>
      <div class="ribbon special first-bg "><?php echo $this->__('special') ?></div>
      <?php endif;?>
      <?php if ($isNew):?>
      <div class="ribbon new first-bg"><?php echo $this->__('new') ?></div>
      <?php endif;?>
       
      
      <a id="<?php echo $_product->getId()?>" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageWidth,$imageHeight); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
   
  
  <?php if (Mage::getStoreConfig('quickview/settings/enabled')):?> 
  <span>  <a class="quickview-button button fa-search-btn first-bg" href="javascript:void(0)" onclick="quickvieShow(this)"><?php echo $this->__('Quick view') ?>  <i class="icon-search"></i> </a> </span><?php endif ?>
    
      <div style="display: none;" class="quickview-loader" onclick="closePopup()" id="quickview-loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif')?>"></div>
      <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
      <?php if($_product->getRatingSummary()): ?>
      <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
      <?php endif; ?>
      <div class="prd-line">
        <div class="content_price"> <?php echo $this->getPriceHtml($_product, true) ?> </div>
      </div>
      <div class="actions"> <a class="btn-circle first-bg-hover" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"> <i class="icon-heart"></i> </a>
        <?php if($_product->isSaleable()): ?>
        <a class="btn-circle first-bg-hover" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"> <i class="icon-shopping-cart"></i> </a>
        <?php else: ?>
        <?php endif; ?>
        
             <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                   <a class="btn-circle first-bg-hover" href="<?php echo $_compareUrl ?>" > <i class="icon-exchange"></i> </a> </div>
                              
                              
                        <?php endif; ?>
       
    </li>
    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
  </ul>
  <?php endif ?>
  <?php endforeach ?>
  <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
  <?php endif; ?>
  <div class="toolbar-bottom"> <?php echo $this->getToolbarHtml() ?> </div>
</div>
<?php endif; ?>
