<?php
$helper				= Mage::helper('lightboxes');
$rel                = $helper->getLightboxRel($helper->getConfig('lightbox_type'));
$class              = $helper->getLightboxClass($helper->getConfig('lightbox_type'));
$mainImageSize      = $helper->getMainImageSize();
$mainImageSize      = array(
                        "380",
                        "270"
                    );
$popUpImageSize     = $helper->getPopupImageSize();
$thumbnailSize      = $helper->getThumbnailImageSize();
$thumbnailSize      = array(
                        "135",
                        "77"
                    );
$includeMainImage	= $helper->getConfig('include_mainimage_in_lightbox');

$mainImageRel		= $rel;
$mainImageClass		= $class;
if($helper->getConfig('lightbox_type') == 'piroboxextended' && !$includeMainImage){
	$mainImageRel	= 'single';
	$mainImageClass = 'pirobox';
}elseif($helper->getConfig('lightbox_type') == 'prettyphoto' && !$includeMainImage){
	$mainImageRel	= 'prettyPhoto';
	$mainImageClass = '';
}elseif(!in_array($helper->getConfig('lightbox_type'),array('piroboxextended', 'prettyphoto')) && !$includeMainImage){
	$mainImageRel	= $rel . '-main';
	$mainImageClass = $class . '-main';
}
?>
<!-- jQuery LightBoxes -->
    <?php if($helper->getConfig('include_jquery', 'lightboxes_confliction') && $helper->getConfig('include_jquery_in', 'lightboxes_confliction') == 'media'): 	?>
		<?php echo $this->getChildHtml('jquery_inclusion'); ?>
	<?php endif; ?>

    <?php if($helper->getConfig('include_lighboxes_in', 'lightboxes_confliction') == 'media'): ?>
		<?php echo $this->getChildHtml('lightboxes_inclusion'); ?>
	<?php endif; ?>

	<?php if($helper->getConfig('include_initialization_in', 'lightboxes_confliction') == 'media'): ?>
		<?php echo $this->getChildHtml('lightboxes_initialization'); ?>
	<?php endif; ?>
<!-- //jQuery LightBoxes -->
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>

<?php
//check if zoomer is disabled
    $noZoom = $helper->getConfig('disable_zoombar');
?>

<section id="product-imgs" class="seven columns">
    <?php if(!$noZoom): ?>
        <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/cloud-zoom.1.0.3.js');?>"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/cloud-zoom.css');?>" media="all" />
    <?php endif; ?>
    <?php if($noZoom):
        $_img = '<img id="product-img-main-img" src="'.$this->helper('catalog/image')->init($_product, 'image')->keepAspectRatio(true)->constrainOnly(true)->resize($mainImageSize[0], $mainImageSize[1]).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        if(empty($popUpImageSize[0]) || empty($popUpImageSize[0])):
            $popUpImage = $this->helper('catalog/image')->init($_product, 'image');
        else:
            $popUpImage = $this->helper('catalog/image')->init($_product, 'image')->resize($popUpImageSize[0], $popUpImageSize[1]);
        endif;
    ?>
        <a id="product-img-main" class="hashborder" href="<?php echo $popUpImage; ?>" rel="<?php echo $mainImageRel; ?>" class="product-img-main<?php echo $mainImageClass; ?>" title="<?php echo $this->htmlEscape($this->getImageLabel()) ?>">
            <div class="hashborder-border"></div>
            <?php echo $_helper->productAttribute($_product, $_img, 'image'); ?>
            <div class="hashborder-border"></div>
        </a>
    <?php endif; ?>
    <?php if(!$noZoom):
        $_img = '<img id="product-img-main-img" src="'.$this->helper('catalog/image')->init($_product, 'image')->keepAspectRatio(true)->constrainOnly(true)->resize($mainImageSize[0], $mainImageSize[1]).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        if(empty($popUpImageSize[0]) || empty($popUpImageSize[0])):
            $popUpImage = $this->helper('catalog/image')->init($_product, 'image');
        else:
            $popUpImage = $this->helper('catalog/image')->init($_product, 'image')->resize($popUpImageSize[0], $popUpImageSize[1]);
        endif;
    ?>
    <a style="position: relative; display: block;"
        href="<?php echo $popUpImage; ?>"
        <?php /*?> rel="tint: '', tintOpacity: 0.9, position: 'right', adjustX: 14, adjustY:0 "<?php */?>
        rel="position: 'inside', adjustX: 0, adjustY:0"
        class="product-image-main hashborder <?php echo $mainImageClass; ?> cloud-zoom"
        title="<?php echo $this->htmlEscape($this->getImageLabel()) ?>">
        <div class="hashborder-border"></div>
        <?php echo $_helper->productAttribute($_product, $_img, 'image'); ?>
        <div class="hashborder-border"></div>
    </a>
    <?php endif; ?>
    <?php if(!$noZoom): ?>
        <p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
        <div class="zoom">
            <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
            <div id="track">
                <div id="handle"></div>
            </div>
            <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
        </div>
        <script type="text/javascript">
            //<![CDATA[
            Event.observe(window, 'load', function() {
                product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
            });
            //]]>
        </script>
    <?php endif; ?>
    <?php $mainPopUpImage = $_product->getImage(); ?>
    <?php if (count($this->getGalleryImages()) > 0):
        ?>
        <section id="product-img-views" class="clearfix">
            <?php
            $gallery = $this->getGalleryImages();
            $count   = 1;
            $max     = 3;
            reset($gallery);
            $first = current($gallery);
            $last  = end($gallery);
            ?>
            <?php foreach ($gallery as $_image):
                if(empty($popUpImageSize[0]) || empty($popUpImageSize[0])):
                    $popUpImage = $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile());
                else:
                    $popUpImage = $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($popUpImageSize[0], $popUpImageSize[1]);
                endif;
                if($_image->getFile()==$mainPopUpImage) continue;
                ?>
                <a href="<?php echo $popUpImage; ?>" rel="<?php echo $mainImageRel; ?>" class="product-img-view hashborder<?php echo ($_image==$first?" first":'').($_image==$last||$count==$max?" last":'').(strlen($class)?$class:''); ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                    <?php /** @see Mage_Catalog_Helper_Image */ ?>
                    <?php //echo dumper::dump((($this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepAspectRatio(true)->resize($thumbnailSize[0],$thumbnailSize[1])))); ?>
                    <img class="product-img-view-thumb" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepAspectRatio(false)->constrainOnly(false)->resize($thumbnailSize[0], $thumbnailSize[1]); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                </a>
            <?php if($count==$max): break; else: $count++; endif;
endforeach; ?>
            <div class="cart-box-border"></div>
        </section>
    <?php endif; ?>
    </section>
<?php endif; ?>
