<section id="cart-btns" class="six columns">
    <div id="cart-subtotal" class="cart-box">
        <div class="cart-box-border"></div>
        <div class="cart-box-inner">
            <h3 id="cart-subtotal-header">Order Subtotal</h3>
            <section id="cart-subtotal-sub">Free Shipping on All Orders</section>
            <table id="cart-subtotal-table">
                <tr id="cart-subtotal-table-title">
                    <th colspan="2">Subtotal:</th>
                </tr>
                <tr id="cart-subtotal-table-items" class="cart-subtotal-table-row clearfix">
                    <th class="cart-subtotal-table-left">Items Total:</th>
                    <td class="cart-subtotal-table-right">$1,834.00</td>
                </tr>
                <tr id="cart-subtotal-table-shipping" class="cart-subtotal-table-row clearfix">
                    <th class="cart-subtotal-table-left">Shipping:</th>
                    <td class="cart-subtotal-table-right">FREE</td>
                </tr>
                <tr id="cart-subtotal-table-shipping" class="cart-subtotal-table-row clearfix">
                    <th class="cart-subtotal-table-left">Order Total:</th>
                    <td class="cart-subtotal-table-right">$1,834.00</td>
                </tr>
            </table>
        </div>
        <div class="cart-box-border"></div>
    </div>
    <section id="cart-continue" class="cart-btn-wrap clearfix">
        <button id="cart-continue-btn" class="cart-btn">Back to Store</button>
    </section>
    <section id="cart-checkout" class="cart-btn-wrap clearfix">
        <button id="cart-checkout-btn" class="cart-btn">Checkout</button>
    </section>
</section>