



<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>


<div class="width-carousel">
        <div class="title-box">
          <h3 class="title-carousel first-brd"><?php echo $this->__('New products') ?></h3>
        </div>
        


      <?php $_columnCount = $this->getColumnCount(); ?>
        <ul class="products-grid first odd bxslider">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <?php endif ?>
      
        
        <li class="item first fadeIn animated">
        
  <a  href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
 <img  src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,180) ?>"  />
            
             <?php /*?> <div class="caption bottom-left"> <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?></div><?php */?>
  
            </a>
            
            <h2 class="product-name">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a>
            </h2>
   
           <div class="actions"> 
    <a class="btn-circle first-bg-hover" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"> <i class="icon-heart"></i> </a> 
    <a class="btn-circle first-bg-hover" href="<?php echo $_product->getProductUrl()?>"> <i class="icon-shopping-cart"></i> </a>
     <a class="btn-circle first-bg-hover" href="<?php echo $_compareUrl ?>"> <i class="icon-exchange"></i> </a> 
     
     </div> 
  
        </li>
        <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        <?php endif ?>
        <?php endforeach; ?>
        
        </ul>
      </div>
      
  
<?php endif; ?>
