<?php
class Rofcustom_Googlecmsimport_Helper_Data extends Mage_Core_Helper_Abstract {

    protected $_releasedPages = array(
        "locations/alabama",
        "locations/alaska",
        "locations/arizona",
        "locations/arkansas",
        "locations/california",
        "locations/colorado",
        "locations/connecticut",
        "locations/delaware",
        "locations/district-of-columbia",
        "locations/florida",
        "locations/georgia",
        "locations/hawaii",
        "locations/idaho",
        "locations/illinois",
        "locations/indiana",
        "locations/iowa",
        "locations/kansas",
        "locations/kentucky",
        "locations/louisiana",
        "locations/maine",
        "locations/maryland",
        "locations/massachusetts",
        "locations/michigan",
        "locations/minnesota",
        "locations/mississippi",
        "locations/missouri",
        "locations/montana",
        "locations/nebraska",
        "locations/nevada",
        "locations/new-hampshire",
        "locations/new-jersey",
        "locations/new-mexico",
        "locations/new-york",
        "locations/north-carolina",
        "locations/north-dakota",
        "locations/ohio",
        "locations/oklahoma",
        "locations/oregon",
        "locations/pennsylvania",
        "locations/rhode-island",
        "locations/south-carolina",
        "locations/south-dakota",
        "locations/tennessee",
        "locations/texas",
        "locations/utah",
        "locations/vermont",
        "locations/virginia",
        "locations/washington",
        "locations/west-virginia",
        "locations/wisconsin",
        "locations/wyoming",
        "locations/new-york/new-york-city",
        "locations/california/los-angeles",
        "locations/illinois/chicago",
        "locations/texas/houston",
        "locations/pennsylvania/philadelphia",
        "locations/arizona/phoenix",
        "locations/texas/san-antonio",
        "locations/california/san-diego",
        "locations/texas/dallas",
        "locations/california/san-jose",
        "locations/texas/austin",
        "locations/florida/jacksonville",
        "locations/indiana/indianapolis",
        "locations/california/san-francisco",
        "locations/ohio/columbus",
        "locations/texas/fort-worth",
        "locations/north-carolina/charlotte",
        "locations/michigan/detroit",
        "locations/texas/el-paso",
        "locations/tennessee/memphis",
        "locations/massachusetts/boston",
        "locations/washington/seattle",
        "locations/colorado/denver",
        "locations/district-of-columbia/washington",
        "locations/tennessee/nashville",
        "locations/maryland/baltimore",
        "locations/kentucky/louisville",
        "locations/oregon/portland",
        "locations/oklahoma/oklahoma-city",
        "locations/wisconsin/milwaukee"
    );

    public function getReleasedPages() {
        return $this->_releasedPages;
    }

    public function isActiveByIdentifier($identifier) {
        return in_array($identifier, $this->_releasedPages);
    }

}