<?php if(count($children = $this->getChildren())>0): ?>
<div class="cms-widget-children-list account-box fourteen columns offset-by-one by-margin add-bottom">
    <div class="account-box-border"></div>
    <div class="account-box-inner">
        <div class="box-head">
            <h2 class="cms-widget-children-list-title">
            <?php if(stristr($_SERVER["REQUEST_URI"],($parent = $this->getParent()))===false): ?>
                <a href="<?php echo $this->getUrl($parent); ?>"><?php echo $this->getTitle(); ?></a>
            <?php else: echo $this->getTitle(); endif; ?>
            </h2>
        </div>
        <div class="box-content">
            <?php $lists        = 0; ?>
            <?php $i            = 0; ?>
            <?php foreach($children as $child): ?>
                <?php if(($i%5)==0): ?>
                <ul class="cms-widget-children-list-link-list">
                <?php endif; ?>
                <li class="cms-widget-children-list-link">
                    <a href="<?php echo $this->getUrl($child['identifier']); ?>"><?php echo $this->escapeHtml($child['title']) ?></a>
                </li>
                <?php if((($i%5)==4) || ($i==(count($citiesList)-1))): ?>
                </ul><?php $lists++; ?>
                <?php endif; ?>
                <?php $i++; ?>
            <?php endforeach; ?>

            <?php if($this->showViewMoreLink()): ?>
            <div class="cms-widget-children-list-more" data-lists="<?php echo $lists; ?>">
                <?php if($lists>1): ?>
                <a class="cms-widget-children-list-more-link" href="#">view more</a>
                <?php else: ?>
                &nbsp;
                <?php endif; ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
    <div class="account-box-border"></div>
</div>
<?php endif; ?>
