
<div class="footer-info first-bg">
  <div class="container_9 clearfix"> <?php echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('footer-banner')->toHtml(); ?> </div>
</div>
<footer class="clearfix second-bg" id="footer">
  <div class="footer-wrap container_9 ">
    <div class="footer-set"> <?php echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('footer-blocks')->toHtml(); ?> </div>
    <footer class="clearfix" id="footer-absolute"> <a class="go-top"  id="scroll-top-img"> <a class="go-top first-bg" href="#" id="scroll-top-img"> <img  src="<?php echo $this->getSkinUrl('images/scrolltop.png');?>"></a> </a>
      <div class="copy"> <?php echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('Copyright')->toHtml(); ?> </div>
      <div class="social"> <?php echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('social-footer')->toHtml(); ?> </div>
    </footer>
  </div>
</footer>
