<?php if(count($this->getCities())>0): ?>
<div class="cms-widget-state-list account-box collapsed">
    <div class="account-box-border"></div>
    <div class="account-box-inner">
        <div class="box-head">
            <h2 class="cms-widget-state-list-title">
            <?php if(stristr($_SERVER["REQUEST_URI"],$this->getState())===false): ?>
                <a href="/locations/<?php echo $this->getState(); ?>"><?php echo ucwords(str_replace("-"," ",$this->getTitle())); ?></a>
            <?php else: echo ucwords(str_replace("-"," ",$this->getTitle())); endif; ?>
            </h2>
        </div>
        <div class="box-content">
            <?php $citiesList   = $this->getCities(); ?>
            <?php $lists        = 0; ?>
            <?php $i            = 0; ?>
            <?php for($i=0;$i<count($citiesList);$i++): ?>
                <?php if(($i%5)==0): ?>
                <ul class="cms-widget-state-list-link-list">
                <?php endif; ?>
                    <?php $stateLink = $citiesList[$i]; ?>
                    <li class="cms-widget-state-list-link">
                        <!-- <?php // echo var_export($stateLink); ?> -->
                        <a href="/<?php echo $stateLink['identifier'] ?>"><?php echo $this->escapeHtml($stateLink['title']) ?></a>
                    </li>
                <?php if((($i%5)==4) || ($i==(count($citiesList)-1))): ?>
                </ul><?php $lists++; ?>
                <?php endif; ?>
            <?php endfor; ?>

            <div class="cms-widget-state-list-more" data-lists="<?php echo $lists; ?>">
                <?php if($lists>1): ?>
                <a class="cms-widget-state-list-more-link" href="#">view more</a>
                <?php else: ?>
                &nbsp;
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="account-box-border"></div>
</div>
<?php endif; ?>
