<?php if ($posts = $this->getRecent()): ?>
    <div class="widget-latest">
      <div class="blog-title"> 
        <h2><?php echo Mage::helper('blog')->__('Read the article'); ?></h2>
        </div>
        <ul>
            <?php foreach ($posts as $post): ?>
                <li class="first-bg-hover">
                
                
                <div class="postTitle">
    <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2></div>
                
                
                
                
  
  </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>