<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_productCollection->addAttributeToSelect(array("parent_url_key"));
    $_helper = $this->helper('catalog/output');
	$imageWidth = Mage::getStoreConfig('quickview/frontend/listwidth');
	$imageHeight = Mage::getStoreConfig('quickview/frontend/listheight');
?>

<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>

<?php else: ?>

<div class="category-products">
  <?php echo $this->getToolbarHtml() ?>
  <?php // List mode ?>
  <?php if($this->getMode()!='grid'): ?>
  <?php $_iterator = 0; ?>
    <?php foreach ($_productCollection as $_product): ?>
    <?php
          $url = $_product->getProductUrl();
          if($categoryParent = $_product->getResource()->getAttribute('parent_url_key')) {
              $categoryParent = $categoryParent->getFrontend()->getValue($_product);
              if($categoryParent) {
                  $categoryParent = "products/" . $categoryParent;
                  $url = $this->getUrl($categoryParent."/".basename($url));
              }
          }
          //$proCats = $_product->getCategoryIds();
          //$pc = end($proCats);
          //$category = Mage::getModel('catalog/category')->load($pc);
          //$categoryParent = $category->getUrlPath();
    ?>
    <section class="category-product four columns<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <a id="category-product-inner-<?php echo $_product->getId()?>" href="<?php echo $url ?>" class="category-product-inner clearfix"  title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
            <img class="category-product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageWidth,$imageHeight); ?>" alt="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>" width="<?php echo $imageWidth;?>"<!-- 200 --> height="<?php echo $imageHeight; ?>"<!-- 142 --> />
            <div class="category-product-img-underline"></div>
            <section class="category-product-title" title="<?php echo $_productNameStripped; ?>">
                <?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
            </section>
            <!--<section class="category-product-collection"><?php /*echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') */?></section>-->
            <?php echo $this->getPriceHtml($_product, true) ?>
            <button class="category-product-add" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><?php echo $this->__("Add to Cart")?></button>
        </a>
    </section>
    <?php endforeach; ?>
  <?php else: ?>
  <?php // Grid Mode ?>
  <?php $_collectionSize = $_productCollection->count() ?>
  <?php $_columnCount = $this->getColumnCount(); ?>
  <?php $i=0; foreach ($_productCollection as $_product): ?>
    <section class="category-product four columns<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
        <?php
            $_productNameStripped = $this->stripTags($_product->getName(), null, true);
            $hasSpecial = ($_product->getSpecialPrice())?true:false;
            $isNew = false;
            $newFrom = strtotime($_product->getNewsFromDate());
            $newTo = strtotime($_product->getNewsToDate());
            if (time()>$newFrom && time()<$newTo){
                $isNew = true;
            }
        ?>
        <?php if(false&&$hasSpecial):?>
            <div class="ribbon special first-bg "><?php echo $this->__('special') ?></div>
        <?php endif;?>
        <?php if(false&&$isNew):?>
            <div class="ribbon new first-bg"><?php echo $this->__('new') ?></div>
        <?php endif;?>
        <?php
        /**
         * @TODO Make this take into account the parent url's parents
         * Currently just assuming parent is in 'products', this will change when we do tiered
         * categories. (aka, sub-categories).
         */
            $url = $_product->getProductUrl();
            if($categoryParent = $_product->getResource()->getAttribute('parent_url_key')) {
                $categoryParent = $categoryParent->getFrontend()->getValue($_product);
                if($categoryParent) {
                    $categoryParent = "products/" . $categoryParent;
                    $url = $this->getUrl($categoryParent."/".basename($url));
                }
            }
            //$proCats = $_product->getCategoryIds();
            //$pc = end($proCats);
            //$category = Mage::getModel('catalog/category')->load($pc);
            //$categoryParent = $category->getUrlPath();
        ?>
        <a data-position="<?php echo $_product->getPosition(); ?>" id="category-product-inner-<?php echo $_product->getId()?>" href="<?php echo $url; ?>" class="category-product-inner clearfix"  title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
            <img class="category-product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageWidth,$imageHeight); ?>" alt="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>" width="<?php echo $imageWidth;?>" height="<?php echo $imageHeight; ?>" /><!-- 200x142 -->
            <div class="category-product-img-underline"></div>
            <section class="category-product-title" title="<?php echo $_productNameStripped; ?>" style="margin: 25px 0;">
                <?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
            </section>
            <!-- <section class="category-product-collection"><?php //echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></section> -->
            <?php echo $this->getPriceHtml($_product, true) ?>
            <button class="category-product-add" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')" title="View more about <?php echo $_productNameStripped; ?>"><?php echo $this->__("View More")?></button>
        </a>
    </section>
  <?php endforeach ?>
  <?php endif; ?>
    <?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/pager.phtml')->toHtml(); ?>
</div>

<?php endif; ?>
