 <?php $posts = $this->getPosts(); ?>

<?php if (count($posts)): ?>
<?php /*?> <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?><?php */?>
    <?php foreach ($posts as $post): ?>
        <div class="postWrapper">
            <div class="postTitle">
                <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                <h3><?php echo $post->getCreatedTime(); ?></h3>
            </div>
            <div class="postContent"><?php echo $post->getPostContent(); ?></div>
            <?php echo $this->getBookmarkHtml($post) ?>
 <?php /*?>           <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div><?php */?>
            
            <div class="post-details">
    <table>
      <tr>
        <td><?php if ($this->getCommentsEnabled()): ?>
        <i class="icon-comment"></i>  <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo $this->__("Comments"); ?> </a></td>
        <td>
          <?php endif; ?>
<i class="icon-user" style="margin-right:7px;"></i><?php echo $post->getUser(); ?></td>
        <td class="first-bg"><a href="<?php echo $post->getAddress(); ?>" style="color:#fff; font-style:italic;"><?php echo $this->__("Read more"); ?></a></td>
      </tr>
    </table>
  </div>
  
  
            
                
                
        </div>
    <?php endforeach; ?> 
<?php /*?> <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?><?php */?>
<?php else: ?>  
    <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>
<?php endif; ?>
