<?php /*?>    <h4 class="title_block"><?php echo Mage::getStoreConfig('blog/blog/title'); ?></h4><?php */?>
    
<div class="block block-news">
      
      
           <h4 class="title_block"><?php echo Mage::helper('blog')->__('Recent Posts'); ?></h4>
            
            
    <div class="block_content">
        <?php if ($posts = $this->getRecent()): ?>
 
          
                <ul>
                    <?php foreach ($posts as $post): ?>
                        <li><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
        
        <?php endif; ?>


    </div>
</div>


        <?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>  
<div class="block block-news">
 <h4 class="title_block"><?php echo Mage::helper('blog')->__('Categories'); ?></h4>
     <div class="block_content">
 
                <ul>
                    <?php $cats = $this->getCategories(); ?>
                    <?php foreach ($cats as $cat): ?>
                        <li><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
</div>
</div>





    

         
        <?php endif; ?>



     <?php echo $this->getChildHtml('blog_tags'); ?>


