<div class="page-title sixteen columns">
    <h1 id="page-heading"><?php echo substr(stristr($this->getLayout()->getBlock("head")->getTitle(),Mage::getStoreConfig('design/head/title_suffix'),true),strlen("Blog - "))." Blog" ?></h1>
    <?php if($this->getMessagesBlock()): ?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
        <script type="text/javascript">
            setTimeout(function() {
                jQuery("ul.messages").slideUp("slow");
            }, 5000);
        </script>
    <?php endif; ?>
    <aside class="back-aside">
        <a href="<?php echo $this->getUrl("blog"); ?>"><?php echo $this->__("&laquo;&nbsp;Back To Latest"); ?></a>
    </aside>
</div>
<?php $post = $this->getPost(); ?>
<div class="account-box fourteen columns offset-by-one by-margin add-bottom">
    <div class="account-box-border"></div>
    <div class="account-box-inner">
        <div class="box-head">
            <h2><?php echo $post->getTitle(); ?></h2>
            <h3 class="box-head-timestamp"><?php echo $post->getCreatedTime(); ?></h3>
        </div>
        <div class="postContent"><?php echo $post->getPostContent(); ?></div>
        <?php echo $this->getBookmarkHtml($post) ?>
        <div class="tags twelve columns offset-by-one by-margin"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
        <?php /*?><div class="postDetails">
            <?php $postCats = $post->getCats(); ?>
            <?php if (!empty($postCats)): ?>
                <?php echo Mage::helper('blog')->__('Posted in'); ?>
                <?php foreach ($postCats as $title => $url): ?>
                    <a href="<?php echo $url; ?>"><?php echo $title; ?></a>
                <?php endforeach; ?>
            <?php else: ?>
                <?php echo Mage::helper('blog')->__('Posted'); ?>
            <?php endif; ?><?php echo $this->__("By"); ?> <h4 class="poster"><?php echo $post->getUser(); ?></h4>
        </div><?php */?>
    </div>
    <div class="account-box-border"></div>
</div>

<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
    <?php $comments = $this->getComment(); ?>
    <div class="post-details">
        <table>
            <tbody>
            <tr>
                <td><i class="icon-comment"></i> <?php echo $this->__('Post Comments') ?></td>
                <td><i class="icon-time"></i><?php echo $post->getCreatedTime(); ?></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="comment-section">
        <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
        <?php foreach ($comments as $comment) : ?>
            <div class="comment-wrap">
                <h4 class="comment-name"><?php echo $comment->getUser(); ?>
                    <span class="time-ago">
                        <?php echo $this->__("posted on") ?>
                        <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?>
                    </span>
                </h4>
                <div class="comment"><?php echo nl2br($comment->getComment()); ?></div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
 

    <?php if ($post->getComments()): ?>
        <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
        <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="" id="postComment" method="post">  
                    <fieldset class="group-select">
                        <h3><?php echo Mage::helper('blog')->__('Submit Comment') ?></h3>
                        <ul class="form-list">
                            <li>
                                <div class="input-box aw-blog-comment-area">
                                    <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="button-set">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                        <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>            

            <?php else: ?>
                <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                <p><a class="reply" href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
            <?php endif ?>

        <?php else: ?>

            <form action="" id="postComment" method="post">
                <fieldset class="group-select">
                    <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                    <ul class="form-list">
                        <li>
                            <div class="input-box">
                                <label for="name" class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label><br />
                                <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                            </div>

                            <div class="input-box">
                                <label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label><br />
                                <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
                            </div>

                            <div class="clear"></div>

                            <div class="input-box aw-blog-comment-area">
                                <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                            </div>
                        </li>
                        <?php if(Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()): ?>
                        <li>
                            <?php
                                require_once 'recaptcha/recaptchalib-aw.php';

                                // Get a key from http://recaptcha.net/api/getkey
                                $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                                $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                                $error = null;

                                echo recaptcha_get_html($publickey, $error);
                            ?>
                        </li>
                        <?php endif; ?>
                    </ul>
                </fieldset>
                <div class="button-set">
                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button class="button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                </div>
            </form>

            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
