





<div class="block block-tags block-news">

<h4 class="title_block"><?php echo Mage::helper('blog')->__('Tags'); ?></h4>

<?php if (Mage::getStoreConfig(AW_Blog_Helper_Config::XML_TAGCLOUD_SIZE) && $this->getCollection()->count()): ?>



     <div class="block_content">
 
       
            <?php foreach ($this->getCollection() as $tag): ?>
               <a class="tag-count-<?php echo $this->getTagWeight($tag) ?>  first-bg" href="<?php echo $this->getTagHref($tag) ?>" rel="nofollow"><?php echo $tag->getTag() ?></a>
            <?php endforeach; ?>  
       
    </div>
<?php endif; ?>

</div>
