<?php $_productCollection = Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect("*")->addAttributeToSort("created_at","desc")->setPageSize(8)?>







<div class="width-carousel">
        <div class="title-box">
          <h3 class="title-carousel first-brd"><?php echo $this->__('Featured products') ?></h3>
        </div>
        

 
        <ul class="products-grid first odd bxslider">
        
        <?php foreach($_productCollection as $_product):?>
  <li class="item first fadeIn animated"> <a href="<?php echo $_product->getProductUrl()?>"  class="product-image"><img width="249" height="180" src="<?php echo $this->helper('catalog/image')->init($_product,"image")->resize($mainImageSize[0], $mainImageSize[1])?>"></a>
    <h2 class="product-name"> <a href="<?php echo $_product->getProductUrl()?>"> <?php echo $_product->getName()?> </a> </h2>
    <div class="actions"> 
    <a class="btn-circle first-bg-hover" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"> <i class="icon-heart"></i> </a> 
    <a class="btn-circle first-bg-hover" href="<?php echo $_product->getProductUrl()?>"> <i class="icon-shopping-cart"></i> </a>
  <?php if($_compareUrl=$this->getLayout()->createBlock('catalog/product_list')->getAddToCompareUrl($_product)): ?>
     <a class="btn-circle first-bg-hover" href="<?php echo $_compareUrl ?>"> <i class="icon-exchange"></i> </a> 
 <?php endif; ?>
     
     </div>
  </li>
  <?php endforeach; ?>
  
  
      
        </ul>
      </div>
      
      
      

      
      
      
      



                            
